version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306' #Not an issue since SQL requires a username and password
    environment:
#      MYSQL_USER: "Brian"
#      MYSQL_PASSWORD: "Destiny2"
      MYSQL_ROOT_PASSWORD: "iloveelephantsmalls"
#      MYSQL_DATABASE: "credentials"
    volumes:
      - dbData:/var/lib/mysql
  app:
    build: .
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - '8080:8080'
volumes:
  dbData:
    driver: local